#!/usr/bin/perl -w

use strict;

use Marklite;
use Template;
use Cwd 'abs_path';
use File::Basename;

my $file = shift;
if (!(-e $file)) { exit; }
my (undef, $dir) = fileparse(abs_path($file));

my $F;
open($F, $file);
my $m;
{
    local $/;
    $m = <$F>;
}
close($F);

$m =~ s{^---\n(.*?)\n---\n\n}{}sm;
my $meta = $1;
my %post;
while ($meta =~ m{^(.*?)\s*:\s*(.*?)\s*$}gsm) {
    $post{$1} = $2;
}
my $M = new Marklite({ marklite => $m, dir => $dir });
$post{content} = $M->out();
$post{template} = $post{template} || 'default';

my $tt = Template->new({
    INCLUDE_PATH => 'templates',
}) || die $Template::ERROR, "\n";

$tt->process($post{template} . ".tt2", { 'post' => \%post });

